### ISSUE TITLE
BUG: rule34 doesn't return anything if random file is too large

### ISSUE THREAD

**Issue by Tatatofly** [Tatatofly/Discordbot-Shiro#21]
rule34 doesn't return anything if random file is too large.

`(node:28453) UnhandledPromiseRejectionWarning: DiscordAPIError: Request entity too large
    at RequestHandler.execute (/home/7/tatatofly/github/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 885)`

**Comment by Tatatofly** [comment]
Quick fix for the bug. Will refactor r34 command someday.
