### ISSUE TITLE
BUG: DiscordAPIError: Missing Access

### ISSUE THREAD

**Issue by Tatatofly** [Tatatofly/Discordbot-Shiro#36]
```
/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async TextChannel.sendTyping (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:190:5) {
  method: 'post',
  path: '/channels/883171937495416892/typing',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}
```

**Comment by Tatatofly** [comment]
```
/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async TextChannel.sendTyping (/home/tatu/Discordbot-Shiro/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:190:5) {
  method: 'post',
  path: '/channels/110373943822540800/typing',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}
```

**Comment by Tatatofly** [comment]
Deleted sendTyping earlier.
